sequenceDiagram
  participant App Server
  participant Authorization Server
  participant Resource Server

  App Server ->> Authorization Server: Get tokens sending Client Credentials(client_id,client secret)
  Authorization Server ->> App Server: Access Token
  App Server ->> Resource Server: Get data sending the token
  Resource Server->>App Server:Return data