sequenceDiagram
  actor User
  participant Browser
  participant App Server
  participant Authorization Server
  participant Resource Server

  User ->> Browser: 
  Browser ->> App Server: GET/index.html
  App Server ->> Browser: Display Login page
  Browser ->> App Server: User Credentials
  App Server ->> Authorization Server: Get tokens sending User Credentials
  Authorization Server ->> App Server: Access Token
  App Server ->> Resource Server: Get data sending the token
  Resource Server->>App Server:Return data
  App Server->>Browser: index.html